on: [workflow_dispatch]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          always-auth: "true"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: yarn

      - name: Install Turbo
        run: yarn global add turbo

      - name: "Automated Version Bump"
        uses: "phips28/gh-action-bump-version@master"
        with:
          version-type: "minor"
          skip-commit: "true"
          skip-tag: "true"
          skip-push: "true"

      - name: Generate components
        run: chmod +x ./generate.sh && ./generate.sh

      - name: Publish packages
        run: yarn publish-packages

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Push changes
        with:
          commit_message: Generated changes [skip ci]
